### PR TITLE
added thymeleaf template engine

### PR DESCRIPTION
**Pull request by dvaillant**
Hi, i added the thymeleaf template engine for Spark. Would you like to include it ?

### CODE REVIEW

**Comment by zephiransas** [comment]
@perwendel 
What is the status of this PR?

**Comment by perwendel** [comment]
@zephiransas @dvaillant 
For some reason, I have mistakenly not included this, well coded, PR since I got it mixed up with another, flawed, PR. I will include this ASAP and release to Maven central, probably before the end of this week.

**Comment by zephiransas** [comment]
@perwendel 
Thanks a lot!!

**Comment by perwendel** [comment]
merged!

**Pull request closed without merging**
