### PR TITLE
Support basic Closure template for Sparkjava

### PR DESCRIPTION
**Pull request by prasannasv**

### CODE REVIEW

**Comment by prasannasv** [comment]
@perwendel - mind taking a look?
This is my first contribution to an open source repo. I did my best to follow the general conventions. Additionally added `final` modifier to all local and member variables (Effective Java habit).

**Comment by tipsy** [comment]
Thanks @prasannasv 

What OS are you on? I'm getting `FileNotFoundException` on Windows.

**Comment by tipsy** [comment]
I see you're using `./src/test/resources/templates/hello.soy` for your template-paths, would be nice if you could change the implementation so you only specified files relative to the resource folder like the other template engines.

**Comment by prasannasv** [comment]
@tipsy Thanks for looking! 
I am in Windows as well. Was the FileNotFoundException for the hello.soy file?
I will see if I can make it relative to the resource folder.

**Comment by tipsy** [comment]
> Was the FileNotFoundException for the hello.soy file?
Yes, I just tried running the example and the test. I get the `FileNotFoundException` both from `mvn test` and from running tests in IntelliJ.

**Comment by prasannasv** [comment]
@tipsy - I have made it as a resource now. I couldn't tell if this fixed your issue or not as both `mvn test` and running it in IntelliJ worked for me independent of this change.

**Comment by tipsy** [comment]
@prasannasv It fixed the `FileNotFoundException`, but I'm getting 

```
com.google.template.soy.error.SoyCompilationException: errors during Soy compilation
In file hello.soy:1:35: parse error at '
': expected eof, {alias, {deltemplate, or {template
{namespace spark.template.closure}
```

Looks like it's related to https://github.com/google/closure-templates/issues/111

**Comment by prasannasv** [comment]
@tipsy fwiw, if you do dos2unix on the hello.soy file and try, it will work. Do you want to wait till google resolves the bug before merging this change?

**Comment by tipsy** [comment]
The majority of our users are on windows systems, so I don't think we can release this as is. You could perhaps do some trickery to convert files before compiling them, but it seems a bit hacky.

**Comment by prasannasv** [comment]
@tipsy - now that the related issue is resolved, do you mind checking again?

**Comment by tipsy** [comment]
Did they release it yet? I don't see any new commits from you bumping the dependency 🤔

**Comment by prasannasv** [comment]
@tipsy that was me being dumb. :| Added a commit with their new release.

**Comment by tipsy** [comment]
Cool, I'll check it out tonight.

**Comment by tipsy** [comment]
Perfect, good work!

**Pull request merged**
