### PR TITLE
added rocker templates

### PR DESCRIPTION
**Pull request by xgp**
Added a module for using [Rocker](https://github.com/fizzed/rocker) templates in Spark. 2 approaches using TemplateEngine and ResponseTransformer based on which way you like to invoke your Rocker templates.

### CODE REVIEW

**Comment by tipsy** [comment]
Thanks @xgp 

Before running your example (from IntelliJ), I get `Error:(12, 61) java: package views does not exist`. After commenting out RocketTransformer and running the examples/test, I get: 

Example: 500 with error
`[qtp18593353-22] INFO com.fizzed.rocker.runtime.RockerRuntime - Rocker template reloading not activated`

Test: `com.fizzed.rocker.TemplateNotFoundException: Compiled template views/hello.rocker.html not found`

**Comment by xgp** [comment]
@tipsy Thanks for taking a look at my pull req.

I don't use IntelliJ, but my guess is that it's because I've got my templates in the test source directory. Rocker templates need to be compiled. In my tests, they are compiled using the rocker-maven-plugin specified in the pom. I build and run the tests with 

```
mvn clean install
```

And. I run the two examples with:

```
mvn exec:java -Dexec.classpathScope=test -Dexec.mainClass="spark.template.rocker.example.RockerEngineExample"

mvn exec:java -Dexec.classpathScope=test -Dexec.mainClass="spark.template.rocker.example.RockerTransformerExample"
```

Is there a way you'd suggest structuring it so it would work for your case? I apologize that I'm not more familiar with how IntelliJ builds and runs

**Comment by xgp** [comment]
@tipsy I downloaded the IntelliJ community edition 2016.3.2 and tried without problems. Here were my steps:

1. Open the pom.xml in IntelliJ, clicked 'import as module'
2. Right clicked on spark-template-engines and select 'build module'
3. Right clicked on spark-template-rocker and select 'build module'
4. Right clicked on RockerEngineExample and select 'Run...'
5. Right clicked on RockerTransformerExample and select 'Run...'

**Comment by tipsy** [comment]
I'll try to have a look later today, but will probably have to be tomorrow.

**Comment by tipsy** [comment]
Sorry this took so long @xgp. Not sure what was wrong with my computer last time, but everything seems to be working fine. Thanks!

**Comment by xgp** [comment]
Thank you!

cc @jjlauer

**Pull request merged**
