### PR TITLE
Jtwig template engine for Spark

### PR DESCRIPTION
**Pull request by eurafa**
Hi,

I wrote this morning a new template engine to use **Jtwig** (based on Twig) template in my views.
Jtwig is a modern, lovely and powerful template engine.
Please check [Jtwig](http://jtwig.org/).

So, I would like to share to Spark community.
What do you think about it?

Please, let me know how to help updating Spark documentation.

Best regards,
Rafa.

### CODE REVIEW

**Comment by tipsy** [comment]
Looks good. You have just followed one of the other implementations, and you have tested that everything is working correctly?

**Comment by eurafa** [comment]
Hi @tipsy.
Of course. I checked the syntax using conditionals, expressions, loop and tags.

I added some basic functions to the sample code.
Please, check latest commit.

**Comment by tipsy** [comment]
Great! I can merge it now, unless you want to make any more changes?

**Comment by eurafa** [comment]
Nice! Go ahead!
Thank you @tipsy!

**Pull request merged**
