### PR TITLE
Added Jade Templates

### PR DESCRIPTION
**Pull request by savethejets**
+ Added Jade Templates through the Jade4J library.

### CODE REVIEW

**Comment by perwendel** [comment]
Sry for not looking at this all this time, I've been on parental leave so Spark has been at bit on hold. I should have been clearer in my last response. I ment a readme.md in the spark-template-jade directory. Please move changes in root readme to the spark-template-jade/README.jd.

**Comment by renner** [comment]
Hey @savethejets, @perwendel: What is the status of this PR, may I help somehow so we can get it merged?

**Comment by perwendel** [comment]
@renner Hey, the README.md changes should not be in the spark-template-engine root folder. It should be in the spark-template-jade. 

The readme says that the jade dependency needs to be added to the pom.xml. That shouldn't be necessary since it's already a dependency in the spark-template-jade pom.xml. 

There are also missing javadoc on public/protected/package members and methods that needs to be added otherwise maven central won't accept the release.

**Comment by renner** [comment]
Ok, thanks @perwendel. Since @savethejets seems to be not currently working on this, I would try to make a new pull request based on his commits fixing the issues you mention.

**Comment by renner** [comment]
This pull request could be closed now since #9 has been merged meanwhile.

**Pull request closed without merging**
